

path: D:\\image_rec_model1\main_dataset  #absolute path to dir
train: images/train
val:   images/val


#classes
names:
    0: person
    1: bicycle
    2: car
    3: motorcycle
    4: airplane
    5: bus
    6: train
    7: truck
    8: boat
    9: traffic light
    10: fire hydrant
    11: stop sign
    12: parking meter
    13: bench
    14: bird
    15: orange_lays
    16: green_lays